---
title: ECOmmunity
class:
  htmlLabels: true
  hideEmptyMembersBox: true
  defaultRenderer: elk
  textHeight: 50
config:
  layout: elk
  elk:
    nodePlacementStrategy: "SIMPLE"
---

classDiagram
  %% ================================
  %%          RELATIONS
  %% ================================
  note "<h1>All Classes of the form<br>
  [Type](API|Service|Repository)<br>
  are dependent on [Type]<br>
  Those relations have are not shown<br>
  for readablity reasons</h1>"

  User --> Fridge
  Product --o Fridge
  Product --> CatalogProduct
  Offer --> Product
  User --> UserType
  User --> Location
  Product --> User
  FoodBank --> Location

  Notification --> NotificationType
  Notification --> User

  Notification --> Product
  Notification --> Offer

  RecipeTemplate ..> Recipe

  Review --> User

  CatalogProduct --* Recipe

  OfferRepository ..> User
  OfferRepository ..> Location
  RecipeRepository ..> RecipeTemplate

  RecipeService --> RecipeRepository
  UserService --> UserRepository

  FridgeService --> ProductRepository
  FridgeService ..> Product

  OfferService --> OfferRepository
  FoodBankService --> FoodBankRepository
  UserService --> UserRepository
  NotificationService --> NotificationRepository
  ReviewService --> ReviewRepository

  OfferAPI --> OfferService
  OfferAPI ..> Product
  OfferAPI ..> Location

  FridgeAPI --> FridgeService
  FridgeAPI ..> Product

  FoodBankAPI --> FoodBankService

  UserAPI --> UserService
  UserAPI ..> UserType
  UserAPI ..> Location

  NotificationAPI --> NotificationService

  RecipeAPI --> RecipeService

  AdminRecipeAPI --> AdminRecipeService
  AdminRecipeAPI ..> RecipeTemplate
  ReviewAPI --> ReviewService

  AdminRecipeService --> RecipeRepository
  AdminRecipeService ..> RecipeTemplate

  AdminProductCatalogAPI --> AdminProductCatalogService

  AdminProductCatalogService --> ProductCatalogRepository

  %% ================================
  %%          DOMAIN LAYER
  %% ================================

  %% namespace domain {
    class Location:::domain {
      +address: String
        +longitude: Float
        +latitude: Float
    }

    class User:::domain {
      +id: String
        +data: UserData
        +fridge: Fridge
        +type: UserType
        +username: String
        +email: String
        %% +passwordHash: String
        +location: Location
    }


    class UserType:::enum {
      <<Enumeration>>
        NORMAL
        PREMIUM
    }

    class Fridge:::domain {
      +productsAndAmounts: List~Pair~Products, Integer~~
    }

    class Offer:::domain {
      +id: String
        +postDate: Date
        +postingUser: User
        %% +reservingUser: User
        +product: Product
        +amountOfPruduct: Integer
    }

    class Product:::domain {
      +id: String
        +name: String
        +owner: User
        +expiryDate: Date
        +catalogReference: CatalogProduct
    }

    class CatalogProduct:::domain {
      +id;
      +catalogName: String
        +type: String
    }

    class Recipe:::domain {
      +id: String
        +ingredientsAndAmounts: List~Pair~CatalogProduct, Integer~~
        +instructions: String
        +is_premium: bool
    }

    class RecipeTemplate:::domain {
      +ingredientIdsAndAmounts: List~Pair~String, Integer~~
        +instructions: String
        +is_premium: bool
    }

    class Notification:::domain {
      +id: String
        +target: User
        +type: NotificationType
        +content: String
        +references: List~Object~
        +unread: bool
    }

    class NotificationType:::enum {
      <<Enumeration>>
        NEARING_EXPIRATION_DATE
        FOOD_EXPIRED
        GOTTEN_RESPONSE_TO_OFFER
    }

    class FoodBank:::domain {
      +id: String
        +name: String
        +location: Location
    }

    class Review:::domain {
      +rating: Integer
      +reviewerId: String
      +revieweeId: String
    }
  %% }


%% ================================
%%          API
%% ================================

  %% namespace API {
    class OfferAPI:::api {
      +postOffer(productId: String, amount: Integer) Offer
        +removeOffer(offerId: String)
        +updateOffer(offerId: String, productId: String, amount: Integer)
        +reserveOffer(offerId: String)
        +getOffersInArea(location: Location, radiusMeters: Integer) List~Offer~
    }

    class FridgeAPI:::api {
      +addProduct(product: Product, amountAdded Integer)
        +removeProduct(product: Product, amountRemoved Integer)
        +getProductsInFridge() List~Product~
    }

    class RecipeAPI:::api {
      +getRecipeSuggestion(userId: String) Recipe
    }

    class AdminRecipeAPI:::api {
      +addRecipe(template: RecipeTemplate) Recipe
        +removeRecipe(recipeId: String)
        +updateRecipe(recipeId: String, template: RecipeTemplate) Recipe
    }

    class AdminProductCatalogAPI:::api {
      +addCatalogProduct(name: String, type: String) CatalogProduct
        +removeCatalogProduct(productId: String)
        +updateCatalogProduct(productId: String, name: String, type: String) CatalogProduct
    }

    class NotificationAPI:::api {
      +getUserNotifications(userId: String) List~Notification~
        +checkUnreadNotifications(userId: String) List~Notification~
    }

    class FoodBankAPI:::api {
      +getFoodBanksInArea(location: Location, radiusMeters: Integer) List~FoodBank~
        +getFoodBankById(foodBankId: String) FoodBank
    }

    class UserAPI:::api {
      +registerUser(username: String, email: String, password: String, type: UserType: location: Location) User
        +logInUser(email: String, password: String) User
        +changeUserType(userId: String, userType: UserType) User
        +changeUserPassword(userId: String, password: String) User
        +changeUserEmail(userId: String, email: String) User
        +changeUserLocation(userId: String, location: Location) User
        +deleteAccount(userId: String)
    }

    class ReviewAPI:::api {
      +reviewUser(review: Review)
        +getAverageRating(revieweeId: String) Float
    }
  %% }

%% ================================
%%          SERVICES
%% ================================

  %% namespace services {

    class UserService:::service {
        +registerUser(username: String, email: String, password: String, type: UserType: location: Location) User
        +logInUser(email: String, password: String) User
        +changeUserType(userId: String, userType: UserType) User
        +changeUserPassword(userId: String, password: String) User
        +changeUserEmail(userId: String, email: String) User
        +changeUserLocation(userId: String, location: Location) User
        +deleteAccount(userId: String)
    }

    class FridgeService:::service {
      +addProduct(userId: String, product: Product, amount: Integer) Product
        +removeProduct(userId: String, productId: String, amount: Integer)
        +updateProductAmount(userId: String, productId: String, amount: Integer)
        +getProductById(productId: String) Product
        +getProductAmountById(productId: String) Integer
    }

    class OfferService:::service {
      +postOffer(productId: String, amount: Integer) Offer
        +removeOffer(offerId: String)
        +updateOffer(offerId: String, productId: String, amount: Integer)
        +getOfferById(offerId: String)
        +reserveOffer(offerId: String, reservingUser: User)
        +getOffersInArea(location: Location, radiusMeters: Interger) List~Offer~
    }

    class RecipeService:::service {
      getRecipeSeggestion(user: User) Recipe
        getRecipeById(recipeId: String) Recipe
    }

    class AdminRecipeService:::service {
      +addRecipe(template: RecipeTemplate) Recipe
        +removeRecipe(recipeId: String)
        +updateRecipe(recipeId: String, template: RecipeTemplate) Recipe
    }

    class AdminProductCatalogService:::service {
      +addCatalogProduct(name: String, type: String) CatalogProduct
        +removeCatalogProduct(productId: String)
        +updateCatalogProduct(productId: String, name: String, type: String) CatalogProduct
    }

    class NotificationService:::service {
      +getUserNotifications(userId: String) List~Notification~
        +checkUnreadNotifications(userId: String) List~Notification~
        +sendNotification(notification: Notification)
    }

    class FoodBankService:::service {
      +getFoodBanksInArea(location: Location, radiusMeters: Integer) List~FoodBank~
        +getFoodBankById(foodBankId: String) FoodBank
    }

    class ReviewService:::service {
      +reviewUser(review: Review)
        +getAverageRating(revieweeId: String) Float
    }
  %% }

%% ================================
%%          REPOSITORIES
%% ================================

  %% namespace repositories {

    class UserRepository:::repository {
      +addUser(username: String, email: String, passwordHash: String, type: UserType, location: Location) User
        +removeUser(userId: String)
        +updateUsername(userId: String, username: String)
        +updateEmail(userId: String, email: String)
        +updatePasswordHash(userId: String, passwordHash: String)
        +updateLocation(userId: String, location: Location)
        +updateType(userId: String, type: UserType)
        +getOffersPostedByUser(user: User) List~Offers~
        +getUserByEmail(email: String)$ User
        +getUserByUsername(username: String)$ User
        +getUserById(userId: String)$ User
    }

    class OfferRepository:::repository {
      +addOffer(+postDate: Date, +userId: String, +product: Product, +amountOfPruduct: Integer) Offer
        +removeOffer(offerId: String)
        +updateOffer(offerId: String, productId: String, amount: Integer) Offer
        +getOfferById(offerId: String) Offer
        +reserveOffer(offerId: String)
        +getOffersInArea(location: Location, radiusMeters: Interger) List~Offer~
    }

    class ProductRepository:::repository {
      +addProduct(product: Product, amount: Integer)
        +updateProductAmount(productId: String, amount: Integer)
        +removeProduct(productId: String, amount: Integer)
        +getProductById(productId: String) Product
        +getProductAmountById(productId: String) Integer
        +getProductsAndAmountsByUserId(userId: String) List~Pair~Product, Integer~~
    }

    class RecipeRepository:::repository {
      +findAndCountProductMatchesToRecipes(productsList: List~Product~, inludePremium: bool) List~Pair~Recipe, Integer~~
        +addRecipe(template: RecipeTemplate) Recipe
        +removeRecipe(recipeId: String)
        +updateRecipe(recipeId: String, template: RecipeTemplate) Recipe
        +getRecipeById(recipeId: String) Recipe
    }

    class ProductCatalogRepository:::repository {
      +addCatalogProduct(name: String, type: String) CatalogProduct
        +removeCatalogProduct(productId: String)
        +updateCatalogProduct(productId: String, name: String, type: String) CatalogProduct
        +getCatalogProductById(productId: String) CatalogProduct
    }

    class NotificationRepository:::repository {
      +getUserNotifications(userId: String) List~Notification~
        +getUserUnreadNotifications(userId: String) List~Notification~
        +getNotificationById(notificationId: String) Notification
        +addNotificationToDB(notification: Notification)
        +deleteNotificationFromDB(notificationId: String)
    }

    class FoodBankRepository:::repository {
      +getFoodBanksInArea(location: Location, radiusMeters: Integer) List~FoodBank~
        +getFoodBankById(foodBankId: String) FoodBank
    }

    class ReviewRepository:::repository {
      +reviewUser(review: Review)
        +getAverageRating(revieweeId: String) Float
    }
  %% }

  classDef domain fill:#caffbf;
  classDef api fill:#ffd6a5;
  classDef service fill:#9bf6ff;
  classDef repository fill:#bdb2ff;
  classDef enum fill:#ffadad;
